config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :reviews do
    resources :comments
    resource :bookmark
  end

  resources :users

  resource :session

  resource :account 

  get "about", to: "pages#about"
  get "terms", to: "pages#terms"

  root "pages#home"






end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  #check if logged in
  before_action :check_login, except: [:index, :show]

  def index
    # this is our list page for our reviews

    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]

    # start with all the reviews
    @reviews = Review.all

    # filtering by price
    if @price.present?
      @reviews = @reviews.where(price: @price)
    end

    # filtering by cuisine
    if @cuisine.present?
      @reviews = @reviews.where(cuisine: @cuisine)
    end

    # search near the location
    if @location.present?
      @reviews = @reviews.near(@location)
    end

  end

  def new
    # the form for adding a new review
    @review = Review.new

  end

  def create

    # take info from the form and add it to the model
    @review = Review.new(form_params)


    #and then associate it with the user
    @review.user = @current_user


    #we want to check if the model can be saved
    # if it is, we're going to the home page again
    if @review.save
      flash[:success] = "Your revier was posted!"

      redirect_to root_path
    #if not, show the same form
    else
      #show the view for same new.html.erb
      render "new"
    end


  end

  def show
    #individual review page
    @review = Review.find(params[:id])
  end

  def destroy
    #find the individual review
    @review = Review.find(params[:id])

    #destroy only if its their own review
    if @review.user == @current_user
      @review.destroy
    end

    #redirect to the homepage
    redirect_to root_path
  end

  def edit
    #find the individual review (to_edit)
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
    #if review is over an hour, redirect
  elsif @review.created_at < 1.hour.ago
      redirect_to review_path(@review)
    end

  end

  def update
    #find the individual review
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
    else
      #update with the new info from the form_for
      if @review.update(form_params)
        #redirect somewhere new
        redirect_to review_path(@review)
      else
        render "edit"
      end
    end

  end

  def form_params
    params.require(:review).permit(:title, :restaurant, :body, :score, :ambiance, :cuisine, :price, :address, :photo)
  end


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :title %>
  <%= f.input :restaurant %>
  <%= f.input :address %>
  <%= f.input :photo %>
  <%= f.input :body %>
  <%= f.input :cuisine %>
  <%= f.input :price %>
  <%= f.input :score %>
  <%= f.input :ambiance %>

  <%= f.button :submit %>
<% end %>


<%# commented out below %>
<% if false %>
<%= form_for @review do |f| %>

  <% if @review.errors.any? %>

  <div class="errors">

    <% @review.errors.full_messages.each do |message| %>
      <p> <%= message %> </p>
    <% end %>

  </div>

  <% end %>

  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :restaurant %>
  <%= f.text_field :restaurant %>
  </p>

  <p>
  <%= f.label :address %>
  <%= f.text_field :address %>
  </p>

  <p>
  <%= f.label :body %>
  <%= f.text_area :body %>
  </p>

  <p>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
  </p>

  <p>
  <%= f.label :price %>
  <%= f.number_field :price %>
  </p>

  <p>
  <%= f.label :score %>
  <%= f.number_field :score %>
  </p>

  <p>
  <%= f.label :ambiance %>
  <%= f.text_field :ambiance %>
  </p>

  <%= f.submit "Save review" %>
<% end %>

<% end %>

app/views/reviews/edit.html.erb
<% content_for :page_title, "Edit your new review" %>


<h3> Edit your restaurant review!</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Your favourite restaurant reviews" %>

  <% # how to filter by both %>
  <nav class="filters">
    <%= active_link_to "All restaurants", root_path, active: {price: nil, cuisine: nil, location: nil} %>

    <div>
      <p> Cuisine Filter: </p>
      <%= active_link_to "American", root_path(cuisine:"American", price: @price, location: @location), active: { cuisine: "American" } %>
      <%= active_link_to "Indian", root_path(cuisine:"Indian", price: @price, location: @location), active: { cuisine: "Indian" } %>
      <%= active_link_to "Mexican", root_path(cuisine:"Mexican", price: @price, location: @location), active: { cuisine: "Mexican" } %>
    </div>

    <div>
      <p> Price Filter: </p>
      <%= active_link_to "$", root_path(price:1, cuisine: @cuisine, location: @location), active: { price: 1 } %>
      <%= active_link_to "$$", root_path(price:2, cuisine: @cuisine, location: @location), active: { price: 2 } %>
      <%= active_link_to "$$$", root_path(price:3, cuisine: @cuisine, location: @location), active: { price: 3 } %>
    </div>

    <p> Location Filter: </p>
    <form action="/">
      <input
      type="text"
      name="location"
      placeholder ="Search location..."
      value="<%= @location %>"
      >

      <input
      type="hidden"
      name="price"
      value="<%= @price %>"
      >

      <input
      type="hidden"
      name="cuisine"
      value="<%= @cuisine %>"
      >
    </form>

  </nav>


<% @reviews.each do |review| %>

  <div class="review">
    <%= link_to review_path(review) do %>

    <%= image_tag review.photo.thumb.url if review.photo.url  %>


      <h2><%= review.title %></h2>
      <p>
        <%= review.cuisine %> -
        <%= pluralize review.comments.count, "comment" %>
      </p>

    <% end %>
  </div>

<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3> Add your new restaurant!</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<%= image_tag @review.photo.url if @review.photo.url  %>

<%= image_tag @review.photo.medium.url if @review.photo.url  %>

<%= image_tag @review.photo.thumb.url if @review.photo.url  %>

<h1> <%= @review.title %> </h1>

<h2> <%= @review.restaurant %> </h2>

<% if is_logged_in? %>

  <p>

    <% if @review.bookmarks.where(user: @current_user).any? %>

    <%= link_to "Unbookmark", review_bookmark_path(@review), method: :delete %>

    <% else %>

    <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>

    <% end %>
  </p>

<% end %>

<h3> Bookmarked by ... </h3>

<ul>
  <% @review.bookmarks.each do |bookmark| %>
    <li><%= bookmark.user.username %></li>
  <% end %>
</ul>


<div class="score">
  <%= @review.score %> / 10
</div>

<div class="user">
  Posted by

  <% if @review.user.present? %>

    <%= link_to @review.user.username, user_path(@review.user) %>

  <% else %>

    Anonymous

  <% end %>

</div>

<% if @review.ambiance.present? %>
  <div class="ambiance">
    Ambiance: <%= @review.ambiance %>
  </div>
<% end %>

<% if @review.price.present? %>
  <div class="price">
    Price: <%= @review.price %>
  </div>
<% end %>

<% if @review.cuisine.present? %>
  <div class="ambiance">
    Cuisine: <%= @review.cuisine %>
  </div>
<% end %>

<div class="body">
  <%= simple_format @review.body %>
</div>

<% if @review.user == @current_user %>
  <div class="actions">

    <% if @review.created_at > 1.hour.ago %>
      <%= link_to "Edit this review", edit_review_path(@review) %>
    <% end %>

    <%= link_to "Delete this review", review_path(@review), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<% end %>

<h3> Comments </h3>

<% @review.comments.order("created_at desc").each do |comment| %>
  <div class="comment">
    <%= simple_format comment.body %>

    <p class="posted">
      Posted by
        <% if comment.user.present? %>
          <%= link_to comment.user.username, user_path(comment.user) %>
        <% else %>
          Anonymous
        <% end %>
    </p>

    <p class="posted"> Posted <%= time_ago_in_words comment.created_at %> ago </p>

  </div>
<% end %>

<h3> Add a comment </h3>

<%= simple_form_for [@review, Comment.new] do |f| %>

  <%= f.input :body %>
  <%= f.button :submit, "Add comment" %>

<% end %>