config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :reviews do
    resources :comments
    resource :bookmark
  end

  resources :users

  resource :session

  resource :account 

  get "about", to: "pages#about"
  get "terms", to: "pages#terms"

  root "pages#home"






end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: {scope: :user}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :body, presence: true

  profanity_filter :body

end

app/models/page.rb
class Page < ApplicationRecord
  validates :url, uniqueness: true

  mount_uploader :photo, ContentImageUploader

end

app/models/review.rb
class Review < ApplicationRecord

  # add an association that has a 1-to-many relationship
  has_many :comments
  has_many :bookmarks

  #add an association to the user
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  #add the photo uploader
  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :body, length: {minimum: 10}
  validates :score, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :restaurant, presence: true
  validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :cuisine, length: {minimum: 3}
  validates :ambiance, length: {minimum: 3}

  validates :address, presence: true

  profanity_filter :body, :title

  def to_param
    id.to_s + "-" + title.parameterize
  end



end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :comments
  has_many :bookmarks


  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def to_param
    username
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController


  before_action :check_login

  def show
    redirect_to edit_account_path
  end

  def edit

  end

  def update
    if @current_user.update(form_params)
      flash[:success] = "Your account was updated!"
    end

    render "edit"
  end

  def form_params
    params.require(:user).permit(:username, :email)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @review = Review.find(params[:review_id])

    @comment = @review.comments.new(params.require(:comment).permit(:body))

    @comment.user = @current_user

    @comment.save

    flash[:success] = "Your comment was posted!"


    #go back to the review show page
    redirect_to review_path(@review)

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @content = Page.find_by(url: "home")

    @highly_rated_reviews = Review.where("score >= 8")

    @featured_reviews = Review.where(is_featured: true)
  end



  def about
    @content = Page.find_by(url: "about")
  end

  def terms
    @content = Page.find_by(url: "terms")
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  #check if logged in
  before_action :check_login, except: [:index, :show]

  def index
    # this is our list page for our reviews

    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]

    # start with all the reviews
    @reviews = Review.all

    # filtering by price
    if @price.present?
      @reviews = @reviews.where(price: @price)
    end

    # filtering by cuisine
    if @cuisine.present?
      @reviews = @reviews.where(cuisine: @cuisine)
    end

    # search near the location
    if @location.present?
      @reviews = @reviews.near(@location)
    end

  end

  def new
    # the form for adding a new review
    @review = Review.new

  end

  def create

    # take info from the form and add it to the model
    @review = Review.new(form_params)


    #and then associate it with the user
    @review.user = @current_user


    #we want to check if the model can be saved
    # if it is, we're going to the home page again
    if @review.save
      flash[:success] = "Your revier was posted!"

      redirect_to root_path
    #if not, show the same form
    else
      #show the view for same new.html.erb
      render "new"
    end


  end

  def show
    #individual review page
    @review = Review.find(params[:id])
  end

  def destroy
    #find the individual review
    @review = Review.find(params[:id])

    #destroy only if its their own review
    if @review.user == @current_user
      @review.destroy
    end

    #redirect to the homepage
    redirect_to root_path
  end

  def edit
    #find the individual review (to_edit)
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
    #if review is over an hour, redirect
  elsif @review.created_at < 1.hour.ago
      redirect_to review_path(@review)
    end

  end

  def update
    #find the individual review
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
    else
      #update with the new info from the form_for
      if @review.update(form_params)
        #redirect somewhere new
        redirect_to review_path(@review)
      else
        render "edit"
      end
    end

  end

  def form_params
    params.require(:review).permit(:title, :restaurant, :body, :score, :ambiance, :cuisine, :price, :address, :photo)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #login form
  end

  def create
    #actually try and log in
    @form_data = params.require(:session)

    #pull out the user and password from the form data
    @username = @form_data[:username]
    @password = @form_data[:password]

    #lets check the user is who they say they are
    @user = User.find_by(username: @username).try(:authenticate, @password)

    #if there is a user present
    if @user

      #save his user to that user's session
      session[:user_id] = @user.id

      redirect_to root_path
    else
      render "new"
    end

  end

  def destroy
    #log us out!
    #remove the session completely
    reset_session

    #redirect_to the log in
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:id])
  end

  def new
    # form for adding a new user
    @user = User.new
  end

  def create
    # take the params from the form
    # create a new user
    @user = User.new(form_params)
    # if its valid and it saves, go to the list users page
    # if not, see the firm with errors
    if @user.save
      # save the session with the user
      session[:user_id] = @user.id

      flash[:success] = "Welcome to Bien Reviews!"

      redirect_to users_path
    else
      render "new"
    end

  end

  def form_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)

  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= content_for :page_title %> - Bien Reviews - The Best Restaurants in the World!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <%= image_tag "bien-logo.svg" %>
          <% end %>
        </h1>
        <%#<h2>The Best Restaurants in the World!</h2>%>
      <nav>

        <% if is_logged_in? %>

          <%= @current_user.username %>

          <% if @current_user.is_admin? %>
            <%= link_to "Admin", admin_root_path %>
          <% end %>

          <%= link_to "About Us", about_path %>
          <%= link_to "Add a Review", new_review_path %>
          <%= link_to "Edit Account", edit_account_path %>
          <%= link_to "Log Out", session_path, method: :delete, data: {confirm: "Are you sure?"} %>


        <% else %>

          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Log in", new_session_path %>

        <% end %>


      </nav>
    </header>


    <% if flash[:success].present? %>
      <div class="success">
        <%= flash[:success] %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer>
      Copyright 2021 Bien Reviews - <%= link_to "Terms & Conditions", terms_path %>
    </footer>

  </body>

</html>

app/views/pages/_review.html.erb
<p>
  <%= link_to review.title, review_path(review) %> (<%= review.score %>/10, rated by
  <% if review.user.present? %>
  <%=review.user.username %>
  <% else %>Anonymous<% end %>)
</p>

app/views/pages/about.html.erb
<h1> <%= @content.title %> </h1>

<%= image_tag @content.photo.url if @content.photo.url  %>


<%= simple_format @content.body %>

app/views/pages/home.html.erb
<h1> <%= @content.title %> </h1>

<%= image_tag @content.photo.url if @content.photo.url  %>


<%= simple_format @content.body %>

<h2> Highly Rated Reviews </h2>

<%= render partial: "review", collection: @highly_rated_reviews %>

<h2> Bien Featured Reviews </h2>

<%= render partial: "review", collection: @featured_reviews %>

app/views/pages/terms.html.erb
<h1> <%= @content.title %> </h1>

<%= simple_format @content.body %>